name: model training 
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.ORIGINAL_SERVICE_ACCOUNT_JSON }}
        run: |
          # Your ML workflow goes here
          
          pip install USG3
          
          python setup.py
          
          
          echo "## Data viz" >> report.md
          cml-publish twi.png --md >> report.md
          cml-publish lidarclass.png --md >> report.md
          cml-publish images/iowa3d.png --md >> report.md
          cml-publish images/upslope.png --md >> report.md
          
          
          cml-send-comment report.md